### ISSUE TITLE
Is this repository still being used?

### ISSUE THREAD

**Issue by jpmckinney** [openc/omnibus-turbot-client#1]
The [`build_version`](https://github.com/openc/omnibus-turbot-client/blob/87da9ec8159f367c9946c59103a1da61a0a28c26/config/projects/turbot-client.rb#L6) is way behind the current version.

If it's not being used, then we should prefix the repo description with `[OBSOLETE]` so that future developers know to ignore it.

/cc @sebbacon

**Comment by sebbacon** [comment]
It's not exactly obsolete. We've not used it for about a year, but it's the only way we found of building a standalone cross-platform binary that worked, after a lot of effort.

We've not used it for a year because we've not done a Flashhacks push for a year where we weren't going to be present.

@inglesp, any thoughts?

**Comment by jpmckinney** [comment]
Does it need to be updated when openc-schema gets updated?

**Comment by sebbacon** [comment]
Not at the moment. In theory we should integrate it into our build process, but I think we should ignore it for now as we're not currently using it.

**Comment by jpmckinney** [comment]
Noting that https://github.com/openc/turbot-client/tree/master/dist is related.
